version: '3.8'

services:
  bot:
    build: .
    container_name: numeric-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    # Добавляем DNS от Google для стабильного сетевого соединения
    dns:
      - 8.8.8.8
      - 1.1.1.1

networks:
  default:
    driver: bridge 